version: '3.8'

services:
  app:
    build:
      context: /back
      dockerfile: Dockerfile
    container_name: back
    environment:
      DATABASE_URL: "file:./file.db"
      JWT_SECRET: "your_secret"
      BCRYPT_SALT_ROUNDS: 10
    command: >
      sh -c "
        npx prisma db push
        node server.js
      "
    ports:
      - "3000:3000"

  front:
    build:
      context: /front
      dockerfile: Dockerfile
    container_name: front
    environment:
      VITE_API_URL : http://back:3000
    ports:
      - "8080:80"
